### ISSUE TITLE
make a navigation bar using bootstrap 

### ISSUE THREAD

**Issue by dhageshubham9** [dhageshubham9/hacktoberfest2021#1]
make a nevigation bar using HTML, CSS, BOOTSTRAP
navigation bar contain HOME, ABOUT-US ,CONTACT-US section 
file name must be :  date_githubid.html

only first 5 candidate will be merged repo so do it as fast as possible

**Comment by vivekarora-02** [comment]
Hey, there!
I would like to contribute to this issue. Please assign me this issue.

ThankYou!
